import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";

const withNextIntl = createNextIntlPlugin("./src/i18n/request.ts");

// Only use standalone output for self-hosted servers, not Vercel
const isVercel = process.env.VERCEL === "1";

const nextConfig: NextConfig = {
  // Standalone output only for self-hosted deployment
  ...(isVercel ? {} : {
    output: "standalone",
    outputFileTracingRoot: __dirname,
  }),

  // Enable Turbopack for faster development (optional)
  // turbopack: {},

  // Experimental features for performance
  experimental: {
    // Optimize CSS loading - reduces render-blocking CSS
    optimizeCss: true,
  },

  // Image optimization
  images: {
    formats: ["image/avif", "image/webp"],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    minimumCacheTTL: 31536000, // 1 year cache for optimized images
  },

  // Enable gzip/brotli compression headers
  compress: true,

  // Power by header (reduces response size slightly)
  poweredByHeader: false,

  // Headers for caching static assets
  async headers() {
    return [
      {
        source: "/images/:path*",
        headers: [
          { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
        ],
      },
      {
        source: "/_next/static/:path*",
        headers: [
          { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
        ],
      },
    ];
  },

  async redirects() {
    return [
      // ============ OLD MILWAUKEE NEIGHBORHOOD URLS ============
      { source: "/Brady-Street-Milwaukee-Wi", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/Downtown-Milwaukee-Wisconsin", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/East-Side-of-Milwaukee", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/Historic-Third-Ward-milwaukee", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/North-Shore-Milwaukee-Wi", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/Riverwest-Milwaukee-Wi", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/West-Allis-Milwaukee-Wi", destination: "/dumpster-rental-milwaukee-wi", permanent: true },

      // ============ TOURISM/LANDMARK PAGES (REDIRECT TO RELEVANT CITY) ============
      { source: "/beaches-in-jacksonville", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/brewery-tour-in-milwaukee", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/brewery-tour-jacksonville", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/jacksonville-riverwalk", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/miller-park", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/milwaukee-county-parks", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/milwaukee-county-zoo", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/museum-of-science-and-history", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/pabst-mansion", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/riverside-arts-market", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/riverside-neighborhood-jacksonville", destination: "/dumpster-rental-jacksonville-fl", permanent: true },

      // ============ FLORIDA CITIES WITH -FL SUFFIX â†’ ACTUAL PAGES (without suffix) ============
      { source: "/dumpster-rental-boynton-beach-fl", destination: "/dumpster-rental-boynton-beach", permanent: true },
      { source: "/dumpster-rental-clearwater-fl", destination: "/dumpster-rental-clearwater", permanent: true },
      { source: "/dumpster-rental-coconut-creek-fl", destination: "/dumpster-rental-coconut-creek", permanent: true },
      { source: "/dumpster-rental-coral-gables-fl", destination: "/dumpster-rental-coral-gables", permanent: true },
      { source: "/dumpster-rental-daytona-beach-fl", destination: "/dumpster-rental-daytona-beach", permanent: true },
      { source: "/dumpster-rental-delray-beach-fl", destination: "/dumpster-rental-delray-beach", permanent: true },
      { source: "/dumpster-rental-hialeah-fl", destination: "/dumpster-rental-hialeah", permanent: true },
      { source: "/dumpster-rental-hollywood-fl", destination: "/dumpster-rental-hollywood", permanent: true },
      { source: "/dumpster-rental-jupiter-fl", destination: "/dumpster-rental-jupiter", permanent: true },
      { source: "/dumpster-rental-lakeland-fl", destination: "/dumpster-rental-lakeland", permanent: true },
      { source: "/dumpster-rental-lauderdale-lakes-fl", destination: "/dumpster-rental-lauderdale-lakes", permanent: true },
      { source: "/dumpster-rental-melbourne-fl", destination: "/dumpster-rental-melbourne", permanent: true },
      { source: "/dumpster-rental-ocoee-fl", destination: "/dumpster-rental-ocoee", permanent: true },
      { source: "/dumpster-rental-ormond-beach-fl", destination: "/dumpster-rental-ormond-beach", permanent: true },
      { source: "/dumpster-rental-palm-bay-fl", destination: "/dumpster-rental-palm-bay", permanent: true },
      { source: "/dumpster-rental-palm-beach-gardens-fl", destination: "/dumpster-rental-palm-beach-gardens", permanent: true },
      { source: "/dumpster-rental-palm-coast-fl", destination: "/dumpster-rental-palm-coast", permanent: true },
      { source: "/dumpster-rental-pembroke-pines-fl", destination: "/dumpster-rental-pembroke-pines", permanent: true },
      { source: "/dumpster-rental-plantation-fl", destination: "/dumpster-rental-plantation", permanent: true },
      { source: "/dumpster-rental-pompano-beach-fl", destination: "/dumpster-rental-pompano-beach", permanent: true },
      { source: "/dumpster-rental-port-orange-fl", destination: "/dumpster-rental-port-orange", permanent: true },
      { source: "/dumpster-rental-port-st-lucie-fl", destination: "/dumpster-rental-port-st-lucie", permanent: true },
      { source: "/dumpster-rental-riviera-beach-fl", destination: "/dumpster-rental-riviera-beach", permanent: true },
      { source: "/dumpster-rental-royal-palm-beach-fl", destination: "/dumpster-rental-royal-palm-beach", permanent: true },
      { source: "/dumpster-rental-st-petersburg-fl", destination: "/dumpster-rental-st-petersburg", permanent: true },
      { source: "/dumpster-rental-wellington-fl", destination: "/dumpster-rental-wellington", permanent: true },
      { source: "/dumpster-rental-west-palm-beach-fl", destination: "/dumpster-rental-west-palm-beach", permanent: true },
      { source: "/dumpster-rental-weston-fl", destination: "/dumpster-rental-weston", permanent: true },
      { source: "/dumpster-rental-winter-haven-fl", destination: "/dumpster-rental-winter-haven", permanent: true },
      { source: "/dumpster-rental-winter-springs-fl", destination: "/dumpster-rental-winter-springs", permanent: true },

      // ============ NEW JERSEY CITIES ============
      { source: "/dumpster-rental-jersey-city-nj", destination: "/dumpster-rental-jersey-city", permanent: true },

      // ============ CORRUPTED/MALFORMED SLUGS ============
      { source: "/dumpster-rental-jackson-al81662586", destination: "/dumpster-rental-jackson-al", permanent: true },

      // ============ MORE FLORIDA CITIES WITH -FL SUFFIX ============
      { source: "/dumpster-rental-miami-gardens-fl", destination: "/dumpster-rental-miami-gardens", permanent: true },
      { source: "/dumpster-rental-altamonte-springs-fl", destination: "/dumpster-rental-altamonte-springs", permanent: true },
      { source: "/dumpster-rental-north-miami-fl", destination: "/dumpster-rental-north-miami", permanent: true },
      { source: "/dumpster-rental-north-lauderdale-fl", destination: "/dumpster-rental-north-lauderdale", permanent: true },
      { source: "/dumpster-rental-pinellas-park-fl", destination: "/dumpster-rental-pinellas-park", permanent: true },
      { source: "/dumpster-rental-pensacola-fl", destination: "/dumpster-rental-pensacola", permanent: true },
      { source: "/dumpster-rental-ocala-fl", destination: "/dumpster-rental-ocala", permanent: true },
      { source: "/dumpster-rental-tamarac-fl", destination: "/dumpster-rental-tamarac", permanent: true },
      { source: "/dumpster-rental-margate-fl", destination: "/dumpster-rental-margate", permanent: true },
      { source: "/dumpster-rental-hallandale-beach-fl", destination: "/dumpster-rental-hallandale-beach", permanent: true },
      { source: "/dumpster-rental-davie-fl", destination: "/dumpster-rental-davie", permanent: true },
      { source: "/dumpster-rental-coral-springs-fl", destination: "/dumpster-rental-coral-springs", permanent: true },
      { source: "/dumpster-rental-apopka-fl", destination: "/dumpster-rental-apopka", permanent: true },
      { source: "/dumpster-rental-north-miami-beach-fl", destination: "/dumpster-rental-north-miami-beach", permanent: true },
      { source: "/dumpster-rental-sanford-fl", destination: "/dumpster-rental-sanford", permanent: true },
      { source: "/dumpster-rental-bradenton-fl", destination: "/dumpster-rental-bradenton", permanent: true },

      // ============ MORE MILWAUKEE TOURISM/LANDMARKS ============
      { source: "/milwaukee-county-war-memorial-center", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/milwaukee-public-market", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/harley-davidson-museum", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/milwaukee-art-museum", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/Walkers-Point-Milwaukee-Wi", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/Bay-View-milwaukee-wi", destination: "/dumpster-rental-milwaukee-wi", permanent: true },

      // ============ MORE JACKSONVILLE TOURISM/NEIGHBORHOODS ============
      { source: "/southside-neighborhood-jacksonville", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/avondale-neighborhood-jacksonville", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/jacksonville-zoo-and-gardens", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/kingsley-plantation", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/beaches-neighborhood-jacksonville", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/ortega-neighborhood-jacksonville", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/five-points-neighborhood-jacksonville", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/fishing-st-johns-river", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/cummer-museum-of-art-and-gardens", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/springfield-neighborhood-jacksonville", destination: "/dumpster-rental-jacksonville-fl", permanent: true },

      // ============ MORE MILWAUKEE TOURISM/LANDMARKS ============
      { source: "/milwaukee-riverwalk", destination: "/dumpster-rental-milwaukee-wi", permanent: true },

      // ============ SYSTEM/FEED PAGES ============
      { source: "/tos", destination: "/", permanent: true },
      { source: "/feed/rss2", destination: "/blog", permanent: true },

      // ============ CASE SENSITIVITY FIXES ============
      { source: "/dumpster-rental-Victorville-CA", destination: "/dumpster-rental-victorville-ca", permanent: true },
      { source: "/Construction-dumpsters", destination: "/construction-dumpster-rental", permanent: true },
      { source: "/construction-dumpsters", destination: "/construction-dumpster-rental", permanent: true },

      // ============ MISSING STATE SUFFIX (GSC 404s) ============
      { source: "/dumpster-rental-bristol", destination: "/dumpster-rental-bristol-ct", permanent: true },

      // ============ LEGACY CHIMNEY SITE PAGES (old domain content) ============
      { source: "/chimney-rebuild", destination: "/", permanent: true },
      { source: "/chimney-repair", destination: "/", permanent: true },
      { source: "/chimney-sweeping", destination: "/", permanent: true },
      { source: "/chimney-inspection", destination: "/", permanent: true },
      { source: "/chimney-crown-repair", destination: "/", permanent: true },
      { source: "/fireplace-cleaning", destination: "/", permanent: true },
      { source: "/bird-guard-installation", destination: "/", permanent: true },
      { source: "/creosote-removal", destination: "/", permanent: true },
      { source: "/location/:path*", destination: "/locations", permanent: true },
      { source: "/privacy-policy", destination: "/tos", permanent: true },
      { source: "/residential-dumpsters", destination: "/residential-dumpster-rental", permanent: true },
      { source: "/murray-hill-neighborhood-jacksonville", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/dumpster-rental-indiana", destination: "/locations", permanent: true },

      // ============ REDIRECT ERRORS (GSC 2026-03-19) ============
      // Blog pages with garbage appended (bot/JS artifacts)
      { source: "/blog/how-to-rent-dumpsterScheduling", destination: "/blog/how-to-rent-dumpster", permanent: true },
      { source: "/blog/how-to-rent-dumpsterPreparation", destination: "/blog/how-to-rent-dumpster", permanent: true },
      { source: "/blog/roll-off-vs-front-load-dumpsterComparisons", destination: "/blog/roll-off-vs-front-load-dumpster", permanent: true },
      { source: "/blog/dumpster-permit-guideRegulations", destination: "/blog/dumpster-permit-guide", permanent: true },
      // Jacksonville with "Tap" appended
      { source: "/dumpster-rental-jacksonvilleTap", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      // san-marco neighborhood (old format)
      { source: "/san-marco-neighborhood-jacksonville", destination: "/dumpster-rental-jacksonville-fl", permanent: true },

      // ============ BULK GSC 404 FIXES (2026-03-19) ============
      { source: "/dumpster-rental-jac", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/dumpster-rental-abilene", destination: "/dumpster-rental-abilene-tx", permanent: true },
      { source: "/dumpster-rental-akron", destination: "/dumpster-rental-akron-oh", permanent: true },
      { source: "/dumpster-rental-alabaster", destination: "/dumpster-rental-alabaster-al", permanent: true },
      { source: "/dumpster-rental-albany", destination: "/dumpster-rental-albany-ga", permanent: true },
      { source: "/dumpster-rental-albertville", destination: "/dumpster-rental-albertville-al", permanent: true },
      { source: "/dumpster-rental-albuquerque", destination: "/dumpster-rental-albuquerque-nm", permanent: true },
      { source: "/dumpster-rental-alexander-city", destination: "/dumpster-rental-alexander-city-al", permanent: true },
      { source: "/dumpster-rental-alexandria", destination: "/dumpster-rental-alexandria-la", permanent: true },
      { source: "/dumpster-rental-allen", destination: "/dumpster-rental-allen-tx", permanent: true },
      { source: "/dumpster-rental-allentown", destination: "/dumpster-rental-allentown-pa", permanent: true },
      { source: "/dumpster-rental-alpharetta", destination: "/dumpster-rental-alpharetta-ga", permanent: true },
      { source: "/dumpster-rental-altoona", destination: "/dumpster-rental-altoona-pa", permanent: true },
      { source: "/dumpster-rental-amarillo", destination: "/dumpster-rental-amarillo-tx", permanent: true },
      { source: "/dumpster-rental-anaheim", destination: "/dumpster-rental-anaheim-ca", permanent: true },
      { source: "/dumpster-rental-anderson", destination: "/dumpster-rental-anderson-in", permanent: true },
      { source: "/dumpster-rental-anniston", destination: "/dumpster-rental-anniston-al", permanent: true },
      { source: "/dumpster-rental-apache-junction", destination: "/dumpster-rental-apache-junction-az", permanent: true },
      { source: "/dumpster-rental-apex", destination: "/dumpster-rental-apex-nc", permanent: true },
      { source: "/dumpster-rental-arab", destination: "/dumpster-rental-arab-al", permanent: true },
      { source: "/dumpster-rental-arlington", destination: "/dumpster-rental-arlington-tx", permanent: true },
      { source: "/dumpster-rental-arlington-heights", destination: "/dumpster-rental-arlington-heights-il", permanent: true },
      { source: "/dumpster-rental-arvada", destination: "/dumpster-rental-arvada-co", permanent: true },
      { source: "/dumpster-rental-asheville", destination: "/dumpster-rental-asheville-nc", permanent: true },
      { source: "/dumpster-rental-athens", destination: "/dumpster-rental-athens-al", permanent: true },
      { source: "/dumpster-rental-atlanta", destination: "/dumpster-rental-atlanta-ga", permanent: true },
      { source: "/dumpster-rental-atmore", destination: "/dumpster-rental-atmore-al", permanent: true },
      { source: "/dumpster-rental-attalla", destination: "/dumpster-rental-attalla-al", permanent: true },
      { source: "/dumpster-rental-attleboro", destination: "/dumpster-rental-attleboro-ma", permanent: true },
      { source: "/dumpster-rental-auburn", destination: "/dumpster-rental-auburn-al", permanent: true },
      { source: "/dumpster-rental-aurora", destination: "/dumpster-rental-aurora-co", permanent: true },
      { source: "/dumpster-rental-austin", destination: "/dumpster-rental-austin-tx", permanent: true },
      { source: "/dumpster-rental-avondale", destination: "/dumpster-rental-avondale-az", permanent: true },
      { source: "/dumpster-rental-bakersfield", destination: "/dumpster-rental-bakersfield-ca", permanent: true },
      { source: "/dumpster-rental-baltimore", destination: "/dumpster-rental-baltimore-md", permanent: true },
      { source: "/dumpster-rental-barnstable-town", destination: "/dumpster-rental-barnstable-town-ma", permanent: true },
      { source: "/dumpster-rental-bartlesville", destination: "/dumpster-rental-bartlesville-ok", permanent: true },
      { source: "/dumpster-rental-bartlett", destination: "/dumpster-rental-bartlett-il", permanent: true },
      { source: "/dumpster-rental-baton-rouge", destination: "/dumpster-rental-baton-rouge-la", permanent: true },
      { source: "/dumpster-rental-bay-minette", destination: "/dumpster-rental-bay-minette-al", permanent: true },
      { source: "/dumpster-rental-beaumont", destination: "/dumpster-rental-beaumont-tx", permanent: true },
      { source: "/dumpster-rental-beavercreek", destination: "/dumpster-rental-beavercreek-oh", permanent: true },
      { source: "/dumpster-rental-beaverton", destination: "/dumpster-rental-beaverton-or", permanent: true },
      { source: "/dumpster-rental-belleville", destination: "/dumpster-rental-belleville-il", permanent: true },
      { source: "/dumpster-rental-bend", destination: "/dumpster-rental-bend-or", permanent: true },
      { source: "/dumpster-rental-benton", destination: "/dumpster-rental-benton-ar", permanent: true },
      { source: "/dumpster-rental-bentonville", destination: "/dumpster-rental-bentonville-ar", permanent: true },
      { source: "/dumpster-rental-berwyn", destination: "/dumpster-rental-berwyn-il", permanent: true },
      { source: "/dumpster-rental-bessemer", destination: "/dumpster-rental-bessemer-al", permanent: true },
      { source: "/dumpster-rental-bethlehem", destination: "/dumpster-rental-bethlehem-pa", permanent: true },
      { source: "/dumpster-rental-biloxi", destination: "/dumpster-rental-biloxi-ms", permanent: true },
      { source: "/dumpster-rental-binghamton", destination: "/dumpster-rental-binghamton-ny", permanent: true },
      { source: "/dumpster-rental-birmingham", destination: "/dumpster-rental-birmingham-al", permanent: true },
      { source: "/dumpster-rental-bloomington", destination: "/dumpster-rental-bloomington-il", permanent: true },
      { source: "/dumpster-rental-boaz", destination: "/dumpster-rental-boaz-al", permanent: true },
      { source: "/dumpster-rental-boise-city", destination: "/dumpster-rental-boise-city-id", permanent: true },
      { source: "/dumpster-rental-bolingbrook", destination: "/dumpster-rental-bolingbrook-il", permanent: true },
      { source: "/dumpster-rental-bossier-city", destination: "/dumpster-rental-bossier-city-la", permanent: true },
      { source: "/dumpster-rental-boston", destination: "/dumpster-rental-boston-ma", permanent: true },
      { source: "/dumpster-rental-boulder", destination: "/dumpster-rental-boulder-co", permanent: true },
      { source: "/dumpster-rental-bountiful", destination: "/dumpster-rental-bountiful-ut", permanent: true },
      { source: "/dumpster-rental-bowling-green", destination: "/dumpster-rental-bowling-green-ky", permanent: true },
      { source: "/dumpster-rental-brewton", destination: "/dumpster-rental-brewton-al", permanent: true },
      { source: "/dumpster-rental-bridgeport", destination: "/dumpster-rental-bridgeport-ct", permanent: true },
      { source: "/dumpster-rental-brockton", destination: "/dumpster-rental-brockton-ma", permanent: true },
      { source: "/dumpster-rental-broken-arrow", destination: "/dumpster-rental-broken-arrow-ok", permanent: true },
      { source: "/dumpster-rental-brooklyn", destination: "/dumpster-rental-brooklyn-ny", permanent: true },
      { source: "/dumpster-rental-broomfield", destination: "/dumpster-rental-broomfield-co", permanent: true },
      { source: "/dumpster-rental-brownsville", destination: "/dumpster-rental-brownsville-tx", permanent: true },
      { source: "/dumpster-rental-buckeye", destination: "/dumpster-rental-buckeye-az", permanent: true },
      { source: "/dumpster-rental-buffalo", destination: "/dumpster-rental-buffalo-ny", permanent: true },
      { source: "/dumpster-rental-buffalo-grove", destination: "/dumpster-rental-buffalo-grove-il", permanent: true },
      { source: "/dumpster-rental-burlington", destination: "/dumpster-rental-burlington-nc", permanent: true },
      { source: "/dumpster-rental-caldwell", destination: "/dumpster-rental-caldwell-id", permanent: true },
      { source: "/dumpster-rental-cambridge", destination: "/dumpster-rental-cambridge-ma", permanent: true },
      { source: "/dumpster-rental-canton", destination: "/dumpster-rental-canton-oh", permanent: true },
      { source: "/dumpster-rental-carmel", destination: "/dumpster-rental-carmel-in", permanent: true },
      { source: "/dumpster-rental-carol-stream", destination: "/dumpster-rental-carol-stream-il", permanent: true },
      { source: "/dumpster-rental-carrollton", destination: "/dumpster-rental-carrollton-tx", permanent: true },
      { source: "/dumpster-rental-cary", destination: "/dumpster-rental-cary-nc", permanent: true },
      { source: "/dumpster-rental-casa-grande", destination: "/dumpster-rental-casa-grande-az", permanent: true },
      { source: "/dumpster-rental-castle-rock", destination: "/dumpster-rental-castle-rock-co", permanent: true },
      { source: "/dumpster-rental-cedar-rapids", destination: "/dumpster-rental-cedar-rapids-ia", permanent: true },
      { source: "/dumpster-rental-centennial", destination: "/dumpster-rental-centennial-co", permanent: true },
      { source: "/dumpster-rental-central", destination: "/dumpster-rental-central-la", permanent: true },
      { source: "/dumpster-rental-chandler", destination: "/dumpster-rental-chandler-az", permanent: true },
      { source: "/dumpster-rental-chapel-hill", destination: "/dumpster-rental-chapel-hill-nc", permanent: true },
      { source: "/dumpster-rental-charlotte", destination: "/dumpster-rental-charlotte-nc", permanent: true },
      { source: "/dumpster-rental-chelsea", destination: "/dumpster-rental-chelsea-ma", permanent: true },
      { source: "/dumpster-rental-chester", destination: "/dumpster-rental-chester-pa", permanent: true },
      { source: "/dumpster-rental-chicago", destination: "/dumpster-rental-chicago-il", permanent: true },
      { source: "/dumpster-rental-chickasaw", destination: "/dumpster-rental-chickasaw-al", permanent: true },
      { source: "/dumpster-rental-chicopee", destination: "/dumpster-rental-chicopee-ma", permanent: true },
      { source: "/dumpster-rental-childersburg", destination: "/dumpster-rental-childersburg-al", permanent: true },
      { source: "/dumpster-rental-chula-vista", destination: "/dumpster-rental-chula-vista-ca", permanent: true },
      { source: "/dumpster-rental-cicero", destination: "/dumpster-rental-cicero-il", permanent: true },
      { source: "/dumpster-rental-cincinnati", destination: "/dumpster-rental-cincinnati-oh", permanent: true },
      { source: "/dumpster-rental-cleveland", destination: "/dumpster-rental-cleveland-oh", permanent: true },
      { source: "/dumpster-rental-cleveland-heights", destination: "/dumpster-rental-cleveland-heights-oh", permanent: true },
      { source: "/dumpster-rental-clinton", destination: "/dumpster-rental-clinton-ms", permanent: true },
      { source: "/dumpster-rental-coeur-d-alene", destination: "/dumpster-rental-coeur-d-alene-id", permanent: true },
      { source: "/dumpster-rental-college-station", destination: "/dumpster-rental-college-station-tx", permanent: true },
      { source: "/dumpster-rental-colorado-springs", destination: "/dumpster-rental-colorado-springs-co", permanent: true },
      { source: "/dumpster-rental-columbia", destination: "/dumpster-rental-columbia-sc", permanent: true },
      { source: "/dumpster-rental-columbus", destination: "/dumpster-rental-columbus-ga", permanent: true },
      { source: "/dumpster-rental-commerce-city", destination: "/dumpster-rental-commerce-city-co", permanent: true },
      { source: "/dumpster-rental-concord", destination: "/dumpster-rental-concord-ca", permanent: true },
      { source: "/dumpster-rental-conway", destination: "/dumpster-rental-conway-ar", permanent: true },
      { source: "/dumpster-rental-corona", destination: "/dumpster-rental-corona-ca", permanent: true },
      { source: "/dumpster-rental-corpus-christi", destination: "/dumpster-rental-corpus-christi-tx", permanent: true },
      { source: "/dumpster-rental-corvallis", destination: "/dumpster-rental-corvallis-or", permanent: true },
      { source: "/dumpster-rental-costa-mesa", destination: "/dumpster-rental-costa-mesa-ca", permanent: true },
      { source: "/dumpster-rental-council-bluffs", destination: "/dumpster-rental-council-bluffs-ia", permanent: true },
      { source: "/dumpster-rental-covington", destination: "/dumpster-rental-covington-ky", permanent: true },
      { source: "/dumpster-rental-crowley", destination: "/dumpster-rental-crowley-la", permanent: true },
      { source: "/dumpster-rental-crystal-lake", destination: "/dumpster-rental-crystal-lake-il", permanent: true },
      { source: "/dumpster-rental-cullman", destination: "/dumpster-rental-cullman-al", permanent: true },
      { source: "/dumpster-rental-cuyahoga-falls", destination: "/dumpster-rental-cuyahoga-falls-oh", permanent: true },
      { source: "/dumpster-rental-dallas", destination: "/dumpster-rental-dallas-tx", permanent: true },
      { source: "/dumpster-rental-danbury", destination: "/dumpster-rental-danbury-ct", permanent: true },
      { source: "/dumpster-rental-daphne", destination: "/dumpster-rental-daphne-al", permanent: true },
      { source: "/dumpster-rental-davenport", destination: "/dumpster-rental-davenport-ia", permanent: true },
      { source: "/dumpster-rental-dayton", destination: "/dumpster-rental-dayton-oh", permanent: true },
      { source: "/dumpster-rental-decatur", destination: "/dumpster-rental-decatur-al", permanent: true },
      { source: "/dumpster-rental-dekalb", destination: "/dumpster-rental-dekalb-il", permanent: true },
      { source: "/dumpster-rental-denton", destination: "/dumpster-rental-denton-tx", permanent: true },
      { source: "/dumpster-rental-denver", destination: "/dumpster-rental-denver-co", permanent: true },
      { source: "/dumpster-rental-des-plaines", destination: "/dumpster-rental-des-plaines-il", permanent: true },
      { source: "/dumpster-rental-detroit", destination: "/dumpster-rental-detroit-mi", permanent: true },
      { source: "/dumpster-rental-dothan", destination: "/dumpster-rental-dothan-al", permanent: true },
      { source: "/dumpster-rental-downers-grove", destination: "/dumpster-rental-downers-grove-il", permanent: true },
      { source: "/dumpster-rental-downey", destination: "/dumpster-rental-downey-ca", permanent: true },
      { source: "/dumpster-rental-draper", destination: "/dumpster-rental-draper-ut", permanent: true },
      { source: "/dumpster-rental-dublin", destination: "/dumpster-rental-dublin-oh", permanent: true },
      { source: "/dumpster-rental-dubuque", destination: "/dumpster-rental-dubuque-ia", permanent: true },
      { source: "/dumpster-rental-durham", destination: "/dumpster-rental-durham-nc", permanent: true },
      { source: "/dumpster-rental-east-hartford", destination: "/dumpster-rental-east-hartford-ct", permanent: true },
      { source: "/dumpster-rental-east-honolulu", destination: "/dumpster-rental-east-honolulu-hi", permanent: true },
      { source: "/dumpster-rental-east-point", destination: "/dumpster-rental-east-point-ga", permanent: true },
      { source: "/dumpster-rental-easton", destination: "/dumpster-rental-easton-pa", permanent: true },
      { source: "/dumpster-rental-edmond", destination: "/dumpster-rental-edmond-ok", permanent: true },
      { source: "/dumpster-rental-el-monte", destination: "/dumpster-rental-el-monte-ca", permanent: true },
      { source: "/dumpster-rental-el-paso", destination: "/dumpster-rental-el-paso-tx", permanent: true },
      { source: "/dumpster-rental-elgin", destination: "/dumpster-rental-elgin-il", permanent: true },
      { source: "/dumpster-rental-elk-grove", destination: "/dumpster-rental-elk-grove-ca", permanent: true },
      { source: "/dumpster-rental-elkhart", destination: "/dumpster-rental-elkhart-in", permanent: true },
      { source: "/dumpster-rental-elmhurst", destination: "/dumpster-rental-elmhurst-il", permanent: true },
      { source: "/dumpster-rental-elmira", destination: "/dumpster-rental-elmira-ny", permanent: true },
      { source: "/dumpster-rental-elmont", destination: "/dumpster-rental-elmont-ny", permanent: true },
      { source: "/dumpster-rental-elyria", destination: "/dumpster-rental-elyria-oh", permanent: true },
      { source: "/dumpster-rental-enid", destination: "/dumpster-rental-enid-ok", permanent: true },
      { source: "/dumpster-rental-escondido", destination: "/dumpster-rental-escondido-ca", permanent: true },
      { source: "/dumpster-rental-euclid", destination: "/dumpster-rental-euclid-oh", permanent: true },
      { source: "/dumpster-rental-eugene", destination: "/dumpster-rental-eugene-or", permanent: true },
      { source: "/dumpster-rental-evanston", destination: "/dumpster-rental-evanston-il", permanent: true },
      { source: "/dumpster-rental-evansville", destination: "/dumpster-rental-evansville-in", permanent: true },
      { source: "/dumpster-rental-ewa-gentry", destination: "/dumpster-rental-ewa-gentry-hi", permanent: true },
      { source: "/dumpster-rental-fairhope", destination: "/dumpster-rental-fairhope-al", permanent: true },
      { source: "/dumpster-rental-fall-river", destination: "/dumpster-rental-fall-river-ma", permanent: true },
      { source: "/dumpster-rental-fayetteville", destination: "/dumpster-rental-fayetteville-ar", permanent: true },
      { source: "/dumpster-rental-findlay", destination: "/dumpster-rental-findlay-oh", permanent: true },
      { source: "/dumpster-rental-fishers", destination: "/dumpster-rental-fishers-in", permanent: true },
      { source: "/dumpster-rental-fitchburg", destination: "/dumpster-rental-fitchburg-ma", permanent: true },
      { source: "/dumpster-rental-florence", destination: "/dumpster-rental-florence-al", permanent: true },
      { source: "/dumpster-rental-foley", destination: "/dumpster-rental-foley-al", permanent: true },
      { source: "/dumpster-rental-fontana", destination: "/dumpster-rental-fontana-ca", permanent: true },
      { source: "/dumpster-rental-fort-collins", destination: "/dumpster-rental-fort-collins-co", permanent: true },
      { source: "/dumpster-rental-fort-payne", destination: "/dumpster-rental-fort-payne-al", permanent: true },
      { source: "/dumpster-rental-fort-smith", destination: "/dumpster-rental-fort-smith-ar", permanent: true },
      { source: "/dumpster-rental-fort-wayne", destination: "/dumpster-rental-fort-wayne-in", permanent: true },
      { source: "/dumpster-rental-fort-worth", destination: "/dumpster-rental-fort-worth-tx", permanent: true },
      { source: "/dumpster-rental-franklin", destination: "/dumpster-rental-franklin-wi", permanent: true },
      { source: "/dumpster-rental-freeport", destination: "/dumpster-rental-freeport-ny", permanent: true },
      { source: "/dumpster-rental-fremont", destination: "/dumpster-rental-fremont-ca", permanent: true },
      { source: "/dumpster-rental-fresno", destination: "/dumpster-rental-fresno-ca", permanent: true },
      { source: "/dumpster-rental-frisco", destination: "/dumpster-rental-frisco-tx", permanent: true },
      { source: "/dumpster-rental-fullerton", destination: "/dumpster-rental-fullerton-ca", permanent: true },
      { source: "/dumpster-rental-gadsden", destination: "/dumpster-rental-gadsden-al", permanent: true },
      { source: "/dumpster-rental-garden-grove", destination: "/dumpster-rental-garden-grove-ca", permanent: true },
      { source: "/dumpster-rental-garland", destination: "/dumpster-rental-garland-tx", permanent: true },
      { source: "/dumpster-rental-gary", destination: "/dumpster-rental-gary-in", permanent: true },
      { source: "/dumpster-rental-gastonia", destination: "/dumpster-rental-gastonia-nc", permanent: true },
      { source: "/dumpster-rental-gilbert", destination: "/dumpster-rental-gilbert-az", permanent: true },
      { source: "/dumpster-rental-glencoe", destination: "/dumpster-rental-glencoe-al", permanent: true },
      { source: "/dumpster-rental-glendale", destination: "/dumpster-rental-glendale-az", permanent: true },
      { source: "/dumpster-rental-glenview", destination: "/dumpster-rental-glenview-il", permanent: true },
      { source: "/dumpster-rental-goodyear", destination: "/dumpster-rental-goodyear-az", permanent: true },
      { source: "/dumpster-rental-grand-junction", destination: "/dumpster-rental-grand-junction-co", permanent: true },
      { source: "/dumpster-rental-grand-prairie", destination: "/dumpster-rental-grand-prairie-tx", permanent: true },
      { source: "/dumpster-rental-grand-rapids", destination: "/dumpster-rental-grand-rapids-mi", permanent: true },
      { source: "/dumpster-rental-grants-pass", destination: "/dumpster-rental-grants-pass-or", permanent: true },
      { source: "/dumpster-rental-greeley", destination: "/dumpster-rental-greeley-co", permanent: true },
      { source: "/dumpster-rental-greenfield", destination: "/dumpster-rental-greenfield-wi", permanent: true },
      { source: "/dumpster-rental-greensboro", destination: "/dumpster-rental-greensboro-nc", permanent: true },
      { source: "/dumpster-rental-greenville", destination: "/dumpster-rental-greenville-ms", permanent: true },
      { source: "/dumpster-rental-greenwood", destination: "/dumpster-rental-greenwood-in", permanent: true },
      { source: "/dumpster-rental-gresham", destination: "/dumpster-rental-gresham-or", permanent: true },
      { source: "/dumpster-rental-gulf-shores", destination: "/dumpster-rental-gulf-shores-al", permanent: true },
      { source: "/dumpster-rental-gulfport", destination: "/dumpster-rental-gulfport-ms", permanent: true },
      { source: "/dumpster-rental-guntersville", destination: "/dumpster-rental-guntersville-al", permanent: true },
      { source: "/dumpster-rental-hamilton", destination: "/dumpster-rental-hamilton-oh", permanent: true },
      { source: "/dumpster-rental-hammond", destination: "/dumpster-rental-hammond-in", permanent: true },
      { source: "/dumpster-rental-harrisburg", destination: "/dumpster-rental-harrisburg-pa", permanent: true },
      { source: "/dumpster-rental-hartford", destination: "/dumpster-rental-hartford-ct", permanent: true },
      { source: "/dumpster-rental-hartselle", destination: "/dumpster-rental-hartselle-al", permanent: true },
      { source: "/dumpster-rental-hattiesburg", destination: "/dumpster-rental-hattiesburg-ms", permanent: true },
      { source: "/dumpster-rental-haverhill", destination: "/dumpster-rental-haverhill-ma", permanent: true },
      { source: "/dumpster-rental-hayward", destination: "/dumpster-rental-hayward-ca", permanent: true },
      { source: "/dumpster-rental-hazleton", destination: "/dumpster-rental-hazleton-pa", permanent: true },
      { source: "/dumpster-rental-hempstead", destination: "/dumpster-rental-hempstead-ny", permanent: true },
      { source: "/dumpster-rental-henderson", destination: "/dumpster-rental-henderson-nv", permanent: true },
      { source: "/dumpster-rental-herriman", destination: "/dumpster-rental-herriman-ut", permanent: true },
      { source: "/dumpster-rental-high-point", destination: "/dumpster-rental-high-point-nc", permanent: true },
      { source: "/dumpster-rental-hillsboro", destination: "/dumpster-rental-hillsboro-or", permanent: true },
      { source: "/dumpster-rental-hilo", destination: "/dumpster-rental-hilo-hi", permanent: true },
      { source: "/dumpster-rental-hoffman-estates", destination: "/dumpster-rental-hoffman-estates-il", permanent: true },
      { source: "/dumpster-rental-holyoke", destination: "/dumpster-rental-holyoke-ma", permanent: true },
      { source: "/dumpster-rental-homewood", destination: "/dumpster-rental-homewood-al", permanent: true },
      { source: "/dumpster-rental-honolulu", destination: "/dumpster-rental-honolulu-hi", permanent: true },
      { source: "/dumpster-rental-hoover", destination: "/dumpster-rental-hoover-al", permanent: true },
      { source: "/dumpster-rental-horn-lake", destination: "/dumpster-rental-horn-lake-ms", permanent: true },
      { source: "/dumpster-rental-hot-springs", destination: "/dumpster-rental-hot-springs-ar", permanent: true },
      { source: "/dumpster-rental-houma", destination: "/dumpster-rental-houma-la", permanent: true },
      { source: "/dumpster-rental-houston", destination: "/dumpster-rental-houston-tx", permanent: true },
      { source: "/dumpster-rental-huber-heights", destination: "/dumpster-rental-huber-heights-oh", permanent: true },
      { source: "/dumpster-rental-huntersville", destination: "/dumpster-rental-huntersville-nc", permanent: true },
      { source: "/dumpster-rental-huntington-beach", destination: "/dumpster-rental-huntington-beach-ca", permanent: true },
      { source: "/dumpster-rental-huntsville", destination: "/dumpster-rental-huntsville-al", permanent: true },
      { source: "/dumpster-rental-hutchinson", destination: "/dumpster-rental-hutchinson-ks", permanent: true },
      { source: "/dumpster-rental-idaho-falls", destination: "/dumpster-rental-idaho-falls-id", permanent: true },
      { source: "/dumpster-rental-indianapolis", destination: "/dumpster-rental-indianapolis-in", permanent: true },
      { source: "/dumpster-rental-inglewood", destination: "/dumpster-rental-inglewood-ca", permanent: true },
      { source: "/dumpster-rental-iowa-city", destination: "/dumpster-rental-iowa-city-ia", permanent: true },
      { source: "/dumpster-rental-irvine", destination: "/dumpster-rental-irvine-ca", permanent: true },
      { source: "/dumpster-rental-irving", destination: "/dumpster-rental-irving-tx", permanent: true },
      { source: "/dumpster-rental-ithaca", destination: "/dumpster-rental-ithaca-ny", permanent: true },
      { source: "/dumpster-rental-jackson", destination: "/dumpster-rental-jackson-al", permanent: true },
      { source: "/dumpster-rental-jamestown", destination: "/dumpster-rental-jamestown-ny", permanent: true },
      { source: "/dumpster-rental-jersey-city", destination: "/dumpster-rental-jersey-city-nj", permanent: true },
      { source: "/dumpster-rental-johns-creek", destination: "/dumpster-rental-johns-creek-ga", permanent: true },
      { source: "/dumpster-rental-johnstown", destination: "/dumpster-rental-johnstown-pa", permanent: true },
      { source: "/dumpster-rental-joliet", destination: "/dumpster-rental-joliet-il", permanent: true },
      { source: "/dumpster-rental-jonesboro", destination: "/dumpster-rental-jonesboro-ar", permanent: true },
      { source: "/dumpster-rental-kahului", destination: "/dumpster-rental-kahului-hi", permanent: true },
      { source: "/dumpster-rental-kailua", destination: "/dumpster-rental-kailua-hi", permanent: true },
      { source: "/dumpster-rental-kaneohe", destination: "/dumpster-rental-kaneohe-hi", permanent: true },
      { source: "/dumpster-rental-kannapolis", destination: "/dumpster-rental-kannapolis-nc", permanent: true },
      { source: "/dumpster-rental-kapolei", destination: "/dumpster-rental-kapolei-hi", permanent: true },
      { source: "/dumpster-rental-keizer", destination: "/dumpster-rental-keizer-or", permanent: true },
      { source: "/dumpster-rental-kenner", destination: "/dumpster-rental-kenner-la", permanent: true },
      { source: "/dumpster-rental-kettering", destination: "/dumpster-rental-kettering-oh", permanent: true },
      { source: "/dumpster-rental-kihei", destination: "/dumpster-rental-kihei-hi", permanent: true },
      { source: "/dumpster-rental-killeen", destination: "/dumpster-rental-killeen-tx", permanent: true },
      { source: "/dumpster-rental-knoxville", destination: "/dumpster-rental-knoxville-tn", permanent: true },
      { source: "/dumpster-rental-kokomo", destination: "/dumpster-rental-kokomo-in", permanent: true },
      { source: "/dumpster-rental-kona", destination: "/dumpster-rental-kona-hi", permanent: true },
      { source: "/dumpster-rental-lafayette", destination: "/dumpster-rental-lafayette-in", permanent: true },
      { source: "/dumpster-rental-lahaina", destination: "/dumpster-rental-lahaina-hi", permanent: true },
      { source: "/dumpster-rental-lake-charles", destination: "/dumpster-rental-lake-charles-la", permanent: true },
      { source: "/dumpster-rental-lake-oswego", destination: "/dumpster-rental-lake-oswego-or", permanent: true },
      { source: "/dumpster-rental-lakewood", destination: "/dumpster-rental-lakewood-co", permanent: true },
      { source: "/dumpster-rental-lancaster", destination: "/dumpster-rental-lancaster-ca", permanent: true },
      { source: "/dumpster-rental-laredo", destination: "/dumpster-rental-laredo-tx", permanent: true },
      { source: "/dumpster-rental-las-vegas", destination: "/dumpster-rental-las-vegas-nv", permanent: true },
      { source: "/dumpster-rental-lawrence", destination: "/dumpster-rental-lawrence-in", permanent: true },
      { source: "/dumpster-rental-lawton", destination: "/dumpster-rental-lawton-ok", permanent: true },
      { source: "/dumpster-rental-layton", destination: "/dumpster-rental-layton-ut", permanent: true },
      { source: "/dumpster-rental-league-city", destination: "/dumpster-rental-league-city-tx", permanent: true },
      { source: "/dumpster-rental-leavenworth", destination: "/dumpster-rental-leavenworth-ks", permanent: true },
      { source: "/dumpster-rental-lebanon", destination: "/dumpster-rental-lebanon-pa", permanent: true },
      { source: "/dumpster-rental-lehi", destination: "/dumpster-rental-lehi-ut", permanent: true },
      { source: "/dumpster-rental-lenexa", destination: "/dumpster-rental-lenexa-ks", permanent: true },
      { source: "/dumpster-rental-leominster", destination: "/dumpster-rental-leominster-ma", permanent: true },
      { source: "/dumpster-rental-lewisville", destination: "/dumpster-rental-lewisville-tx", permanent: true },
      { source: "/dumpster-rental-lexington", destination: "/dumpster-rental-lexington-ky", permanent: true },
      { source: "/dumpster-rental-lima", destination: "/dumpster-rental-lima-oh", permanent: true },
      { source: "/dumpster-rental-lincoln", destination: "/dumpster-rental-lincoln-al", permanent: true },
      { source: "/dumpster-rental-little-rock", destination: "/dumpster-rental-little-rock-ar", permanent: true },
      { source: "/dumpster-rental-littleton", destination: "/dumpster-rental-littleton-co", permanent: true },
      { source: "/dumpster-rental-logan", destination: "/dumpster-rental-logan-ut", permanent: true },
      { source: "/dumpster-rental-lombard", destination: "/dumpster-rental-lombard-il", permanent: true },
      { source: "/dumpster-rental-long-beach", destination: "/dumpster-rental-long-beach-ca", permanent: true },
      { source: "/dumpster-rental-longmont", destination: "/dumpster-rental-longmont-co", permanent: true },
      { source: "/dumpster-rental-lorain", destination: "/dumpster-rental-lorain-oh", permanent: true },
      { source: "/dumpster-rental-los-angeles", destination: "/dumpster-rental-los-angeles-ca", permanent: true },
      { source: "/dumpster-rental-louisville", destination: "/dumpster-rental-louisville-ky", permanent: true },
      { source: "/dumpster-rental-loveland", destination: "/dumpster-rental-loveland-co", permanent: true },
      { source: "/dumpster-rental-lowell", destination: "/dumpster-rental-lowell-ma", permanent: true },
      { source: "/dumpster-rental-lubbock", destination: "/dumpster-rental-lubbock-tx", permanent: true },
      { source: "/dumpster-rental-lynn", destination: "/dumpster-rental-lynn-ma", permanent: true },
      { source: "/dumpster-rental-macon", destination: "/dumpster-rental-macon-ga", permanent: true },
      { source: "/dumpster-rental-madison", destination: "/dumpster-rental-madison-al", permanent: true },
      { source: "/dumpster-rental-malden", destination: "/dumpster-rental-malden-ma", permanent: true },
      { source: "/dumpster-rental-mandeville", destination: "/dumpster-rental-mandeville-la", permanent: true },
      { source: "/dumpster-rental-manhattan", destination: "/dumpster-rental-manhattan-ks", permanent: true },
      { source: "/dumpster-rental-mansfield", destination: "/dumpster-rental-mansfield-oh", permanent: true },
      { source: "/dumpster-rental-marana", destination: "/dumpster-rental-marana-az", permanent: true },
      { source: "/dumpster-rental-maricopa", destination: "/dumpster-rental-maricopa-az", permanent: true },
      { source: "/dumpster-rental-marietta", destination: "/dumpster-rental-marietta-ga", permanent: true },
      { source: "/dumpster-rental-mcallen", destination: "/dumpster-rental-mcallen-tx", permanent: true },
      { source: "/dumpster-rental-mckeesport", destination: "/dumpster-rental-mckeesport-pa", permanent: true },
      { source: "/dumpster-rental-mckinney", destination: "/dumpster-rental-mckinney-tx", permanent: true },
      { source: "/dumpster-rental-medford", destination: "/dumpster-rental-medford-ma", permanent: true },
      { source: "/dumpster-rental-memphis", destination: "/dumpster-rental-memphis-tn", permanent: true },
      { source: "/dumpster-rental-mentor", destination: "/dumpster-rental-mentor-oh", permanent: true },
      { source: "/dumpster-rental-mequon", destination: "/dumpster-rental-mequon-wi", permanent: true },
      { source: "/dumpster-rental-meriden", destination: "/dumpster-rental-meriden-ct", permanent: true },
      { source: "/dumpster-rental-meridian", destination: "/dumpster-rental-meridian-id", permanent: true },
      { source: "/dumpster-rental-mesa", destination: "/dumpster-rental-mesa-az", permanent: true },
      { source: "/dumpster-rental-mesquite", destination: "/dumpster-rental-mesquite-tx", permanent: true },
      { source: "/dumpster-rental-metairie", destination: "/dumpster-rental-metairie-la", permanent: true },
      { source: "/dumpster-rental-methuen", destination: "/dumpster-rental-methuen-ma", permanent: true },
      { source: "/dumpster-rental-middletown", destination: "/dumpster-rental-middletown-ct", permanent: true },
      { source: "/dumpster-rental-midland", destination: "/dumpster-rental-midland-tx", permanent: true },
      { source: "/dumpster-rental-midwest-city", destination: "/dumpster-rental-midwest-city-ok", permanent: true },
      { source: "/dumpster-rental-milford", destination: "/dumpster-rental-milford-ct", permanent: true },
      { source: "/dumpster-rental-mililani-town", destination: "/dumpster-rental-mililani-town-hi", permanent: true },
      { source: "/dumpster-rental-millcreek", destination: "/dumpster-rental-millcreek-ut", permanent: true },
      { source: "/dumpster-rental-milwaukee", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/dumpster-rental-minneapolis", destination: "/dumpster-rental-minneapolis-mn", permanent: true },
      { source: "/dumpster-rental-mishawaka", destination: "/dumpster-rental-mishawaka-in", permanent: true },
      { source: "/dumpster-rental-mobile", destination: "/dumpster-rental-mobile-al", permanent: true },
      { source: "/dumpster-rental-modesto", destination: "/dumpster-rental-modesto-ca", permanent: true },
      { source: "/dumpster-rental-moline", destination: "/dumpster-rental-moline-il", permanent: true },
      { source: "/dumpster-rental-monroe", destination: "/dumpster-rental-monroe-la", permanent: true },
      { source: "/dumpster-rental-monroeville", destination: "/dumpster-rental-monroeville-al", permanent: true },
      { source: "/dumpster-rental-montevallo", destination: "/dumpster-rental-montevallo-al", permanent: true },
      { source: "/dumpster-rental-montgomery", destination: "/dumpster-rental-montgomery-al", permanent: true },
      { source: "/dumpster-rental-moore", destination: "/dumpster-rental-moore-ok", permanent: true },
      { source: "/dumpster-rental-moreno-valley", destination: "/dumpster-rental-moreno-valley-ca", permanent: true },
      { source: "/dumpster-rental-morgan-city", destination: "/dumpster-rental-morgan-city-la", permanent: true },
      { source: "/dumpster-rental-mount-prospect", destination: "/dumpster-rental-mount-prospect-il", permanent: true },
      { source: "/dumpster-rental-mount-vernon", destination: "/dumpster-rental-mount-vernon-ny", permanent: true },
      { source: "/dumpster-rental-muncie", destination: "/dumpster-rental-muncie-in", permanent: true },
      { source: "/dumpster-rental-murray", destination: "/dumpster-rental-murray-ut", permanent: true },
      { source: "/dumpster-rental-muscle-shoals", destination: "/dumpster-rental-muscle-shoals-al", permanent: true },
      { source: "/dumpster-rental-muskogee", destination: "/dumpster-rental-muskogee-ok", permanent: true },
      { source: "/dumpster-rental-nampa", destination: "/dumpster-rental-nampa-id", permanent: true },
      { source: "/dumpster-rental-naperville", destination: "/dumpster-rental-naperville-il", permanent: true },
      { source: "/dumpster-rental-nashua", destination: "/dumpster-rental-nashua-nh", permanent: true },
      { source: "/dumpster-rental-nashville", destination: "/dumpster-rental-nashville-tn", permanent: true },
      { source: "/dumpster-rental-natchitoches", destination: "/dumpster-rental-natchitoches-la", permanent: true },
      { source: "/dumpster-rental-new-bedford", destination: "/dumpster-rental-new-bedford-ma", permanent: true },
      { source: "/dumpster-rental-new-britain", destination: "/dumpster-rental-new-britain-ct", permanent: true },
      { source: "/dumpster-rental-new-haven", destination: "/dumpster-rental-new-haven-ct", permanent: true },
      { source: "/dumpster-rental-new-orleans", destination: "/dumpster-rental-new-orleans-la", permanent: true },
      { source: "/dumpster-rental-new-rochelle", destination: "/dumpster-rental-new-rochelle-ny", permanent: true },
      { source: "/dumpster-rental-new-york-city", destination: "/dumpster-rental-new-york-city-ny", permanent: true },
      { source: "/dumpster-rental-newark", destination: "/dumpster-rental-newark-nj", permanent: true },
      { source: "/dumpster-rental-newton", destination: "/dumpster-rental-newton-ma", permanent: true },
      { source: "/dumpster-rental-niagara-falls", destination: "/dumpster-rental-niagara-falls-ny", permanent: true },
      { source: "/dumpster-rental-noblesville", destination: "/dumpster-rental-noblesville-in", permanent: true },
      { source: "/dumpster-rental-normal", destination: "/dumpster-rental-normal-il", permanent: true },
      { source: "/dumpster-rental-norman", destination: "/dumpster-rental-norman-ok", permanent: true },
      { source: "/dumpster-rental-norristown", destination: "/dumpster-rental-norristown-pa", permanent: true },
      { source: "/dumpster-rental-north-hollywood", destination: "/dumpster-rental-north-hollywood-ca", permanent: true },
      { source: "/dumpster-rental-north-las-vegas", destination: "/dumpster-rental-north-las-vegas-nv", permanent: true },
      { source: "/dumpster-rental-north-little-rock", destination: "/dumpster-rental-north-little-rock-ar", permanent: true },
      { source: "/dumpster-rental-norwalk", destination: "/dumpster-rental-norwalk-ct", permanent: true },
      { source: "/dumpster-rental-norwich", destination: "/dumpster-rental-norwich-ct", permanent: true },
      { source: "/dumpster-rental-oak-lawn", destination: "/dumpster-rental-oak-lawn-il", permanent: true },
      { source: "/dumpster-rental-oak-park", destination: "/dumpster-rental-oak-park-il", permanent: true },
      { source: "/dumpster-rental-oakland", destination: "/dumpster-rental-oakland-ca", permanent: true },
      { source: "/dumpster-rental-oceanside", destination: "/dumpster-rental-oceanside-ca", permanent: true },
      { source: "/dumpster-rental-odessa", destination: "/dumpster-rental-odessa-tx", permanent: true },
      { source: "/dumpster-rental-ogden", destination: "/dumpster-rental-ogden-ut", permanent: true },
      { source: "/dumpster-rental-oklahoma-city", destination: "/dumpster-rental-oklahoma-city-ok", permanent: true },
      { source: "/dumpster-rental-olathe", destination: "/dumpster-rental-olathe-ks", permanent: true },
      { source: "/dumpster-rental-olive-branch", destination: "/dumpster-rental-olive-branch-ms", permanent: true },
      { source: "/dumpster-rental-omaha", destination: "/dumpster-rental-omaha-ne", permanent: true },
      { source: "/dumpster-rental-ontario", destination: "/dumpster-rental-ontario-ca", permanent: true },
      { source: "/dumpster-rental-opelousas", destination: "/dumpster-rental-opelousas-la", permanent: true },
      { source: "/dumpster-rental-orange", destination: "/dumpster-rental-orange-ca", permanent: true },
      { source: "/dumpster-rental-orange-beach", destination: "/dumpster-rental-orange-beach-al", permanent: true },
      { source: "/dumpster-rental-orange-county", destination: "/dumpster-rental-orange-county-ca", permanent: true },
      { source: "/dumpster-rental-orem", destination: "/dumpster-rental-orem-ut", permanent: true },
      { source: "/dumpster-rental-orland-park", destination: "/dumpster-rental-orland-park-il", permanent: true },
      { source: "/dumpster-rental-oro-valley", destination: "/dumpster-rental-oro-valley-az", permanent: true },
      { source: "/dumpster-rental-overland-park", destination: "/dumpster-rental-overland-park-ks", permanent: true },
      { source: "/dumpster-rental-owensboro", destination: "/dumpster-rental-owensboro-ky", permanent: true },
      { source: "/dumpster-rental-oxford", destination: "/dumpster-rental-oxford-al", permanent: true },
      { source: "/dumpster-rental-oxnard", destination: "/dumpster-rental-oxnard-ca", permanent: true },
      { source: "/dumpster-rental-palatine", destination: "/dumpster-rental-palatine-il", permanent: true },
      { source: "/dumpster-rental-palmdale", destination: "/dumpster-rental-palmdale-ca", permanent: true },
      { source: "/dumpster-rental-parker", destination: "/dumpster-rental-parker-co", permanent: true },
      { source: "/dumpster-rental-parma", destination: "/dumpster-rental-parma-oh", permanent: true },
      { source: "/dumpster-rental-pasadena", destination: "/dumpster-rental-pasadena-ca", permanent: true },
      { source: "/dumpster-rental-peabody", destination: "/dumpster-rental-peabody-ma", permanent: true },
      { source: "/dumpster-rental-pearl", destination: "/dumpster-rental-pearl-ms", permanent: true },
      { source: "/dumpster-rental-pearl-city", destination: "/dumpster-rental-pearl-city-hi", permanent: true },
      { source: "/dumpster-rental-pearland", destination: "/dumpster-rental-pearland-tx", permanent: true },
      { source: "/dumpster-rental-peoria", destination: "/dumpster-rental-peoria-az", permanent: true },
      { source: "/dumpster-rental-phenix-city", destination: "/dumpster-rental-phenix-city-al", permanent: true },
      { source: "/dumpster-rental-philadelphia", destination: "/dumpster-rental-philadelphia-pa", permanent: true },
      { source: "/dumpster-rental-phoenix", destination: "/dumpster-rental-phoenix-az", permanent: true },
      { source: "/dumpster-rental-piedmont", destination: "/dumpster-rental-piedmont-al", permanent: true },
      { source: "/dumpster-rental-pine-bluff", destination: "/dumpster-rental-pine-bluff-ar", permanent: true },
      { source: "/dumpster-rental-pittsburg", destination: "/dumpster-rental-pittsburg-pa", permanent: true },
      { source: "/dumpster-rental-pittsburgh", destination: "/dumpster-rental-pittsburgh-pa", permanent: true },
      { source: "/dumpster-rental-pittsfield", destination: "/dumpster-rental-pittsfield-ma", permanent: true },
      { source: "/dumpster-rental-plano", destination: "/dumpster-rental-plano-tx", permanent: true },
      { source: "/dumpster-rental-pocatello", destination: "/dumpster-rental-pocatello-id", permanent: true },
      { source: "/dumpster-rental-pomona", destination: "/dumpster-rental-pomona-ca", permanent: true },
      { source: "/dumpster-rental-port-chester", destination: "/dumpster-rental-port-chester-ny", permanent: true },
      { source: "/dumpster-rental-portland", destination: "/dumpster-rental-portland-or", permanent: true },
      { source: "/dumpster-rental-poughkeepsie", destination: "/dumpster-rental-poughkeepsie-ny", permanent: true },
      { source: "/dumpster-rental-prichard", destination: "/dumpster-rental-prichard-al", permanent: true },
      { source: "/dumpster-rental-provo", destination: "/dumpster-rental-provo-ut", permanent: true },
      { source: "/dumpster-rental-pueblo", destination: "/dumpster-rental-pueblo-co", permanent: true },
      { source: "/dumpster-rental-queens", destination: "/dumpster-rental-queens-ny", permanent: true },
      { source: "/dumpster-rental-quincy", destination: "/dumpster-rental-quincy-ma", permanent: true },
      { source: "/dumpster-rental-rainbow-city", destination: "/dumpster-rental-rainbow-city-al", permanent: true },
      { source: "/dumpster-rental-rainsville", destination: "/dumpster-rental-rainsville-al", permanent: true },
      { source: "/dumpster-rental-raleigh", destination: "/dumpster-rental-raleigh-nc", permanent: true },
      { source: "/dumpster-rental-rancho-cucamonga", destination: "/dumpster-rental-rancho-cucamonga-ca", permanent: true },
      { source: "/dumpster-rental-reading", destination: "/dumpster-rental-reading-pa", permanent: true },
      { source: "/dumpster-rental-reno", destination: "/dumpster-rental-reno-nv", permanent: true },
      { source: "/dumpster-rental-revere", destination: "/dumpster-rental-revere-ma", permanent: true },
      { source: "/dumpster-rental-richardson", destination: "/dumpster-rental-richardson-tx", permanent: true },
      { source: "/dumpster-rental-richmond", destination: "/dumpster-rental-richmond-ca", permanent: true },
      { source: "/dumpster-rental-riverside", destination: "/dumpster-rental-riverside-ca", permanent: true },
      { source: "/dumpster-rental-riverton", destination: "/dumpster-rental-riverton-ut", permanent: true },
      { source: "/dumpster-rental-robertsdale", destination: "/dumpster-rental-robertsdale-al", permanent: true },
      { source: "/dumpster-rental-rochester", destination: "/dumpster-rental-rochester-ny", permanent: true },
      { source: "/dumpster-rental-rock-hill", destination: "/dumpster-rental-rock-hill-sc", permanent: true },
      { source: "/dumpster-rental-rockford", destination: "/dumpster-rental-rockford-il", permanent: true },
      { source: "/dumpster-rental-rocky-mount", destination: "/dumpster-rental-rocky-mount-nc", permanent: true },
      { source: "/dumpster-rental-rogers", destination: "/dumpster-rental-rogers-ar", permanent: true },
      { source: "/dumpster-rental-rome", destination: "/dumpster-rental-rome-ga", permanent: true },
      { source: "/dumpster-rental-roseville", destination: "/dumpster-rental-roseville-ca", permanent: true },
      { source: "/dumpster-rental-roswell", destination: "/dumpster-rental-roswell-ga", permanent: true },
      { source: "/dumpster-rental-round-rock", destination: "/dumpster-rental-round-rock-tx", permanent: true },
      { source: "/dumpster-rental-russellville", destination: "/dumpster-rental-russellville-al", permanent: true },
      { source: "/dumpster-rental-ruston", destination: "/dumpster-rental-ruston-la", permanent: true },
      { source: "/dumpster-rental-sacramento", destination: "/dumpster-rental-sacramento-ca", permanent: true },
      { source: "/dumpster-rental-salem", destination: "/dumpster-rental-salem-ma", permanent: true },
      { source: "/dumpster-rental-salina", destination: "/dumpster-rental-salina-ks", permanent: true },
      { source: "/dumpster-rental-salinas", destination: "/dumpster-rental-salinas-ca", permanent: true },
      { source: "/dumpster-rental-salt-lake-city", destination: "/dumpster-rental-salt-lake-city-ut", permanent: true },
      { source: "/dumpster-rental-san-angelo", destination: "/dumpster-rental-san-angelo-tx", permanent: true },
      { source: "/dumpster-rental-san-antonio", destination: "/dumpster-rental-san-antonio-tx", permanent: true },
      { source: "/dumpster-rental-san-bernardino", destination: "/dumpster-rental-san-bernardino-ca", permanent: true },
      { source: "/dumpster-rental-san-diego", destination: "/dumpster-rental-san-diego-ca", permanent: true },
      { source: "/dumpster-rental-san-francisco", destination: "/dumpster-rental-san-francisco-ca", permanent: true },
      { source: "/dumpster-rental-san-jose", destination: "/dumpster-rental-san-jose-ca", permanent: true },
      { source: "/dumpster-rental-sandy", destination: "/dumpster-rental-sandy-ut", permanent: true },
      { source: "/dumpster-rental-sandy-springs", destination: "/dumpster-rental-sandy-springs-ga", permanent: true },
      { source: "/dumpster-rental-santa-ana", destination: "/dumpster-rental-santa-ana-ca", permanent: true },
      { source: "/dumpster-rental-santa-clarita", destination: "/dumpster-rental-santa-clarita-ca", permanent: true },
      { source: "/dumpster-rental-santa-rosa", destination: "/dumpster-rental-santa-rosa-ca", permanent: true },
      { source: "/dumpster-rental-saraland", destination: "/dumpster-rental-saraland-al", permanent: true },
      { source: "/dumpster-rental-satsuma", destination: "/dumpster-rental-satsuma-al", permanent: true },
      { source: "/dumpster-rental-savannah", destination: "/dumpster-rental-savannah-ga", permanent: true },
      { source: "/dumpster-rental-schaumburg", destination: "/dumpster-rental-schaumburg-il", permanent: true },
      { source: "/dumpster-rental-schenectady", destination: "/dumpster-rental-schenectady-ny", permanent: true },
      { source: "/dumpster-rental-scottsboro", destination: "/dumpster-rental-scottsboro-al", permanent: true },
      { source: "/dumpster-rental-scottsdale", destination: "/dumpster-rental-scottsdale-az", permanent: true },
      { source: "/dumpster-rental-scranton", destination: "/dumpster-rental-scranton-pa", permanent: true },
      { source: "/dumpster-rental-seattle", destination: "/dumpster-rental-seattle-wa", permanent: true },
      { source: "/dumpster-rental-selma", destination: "/dumpster-rental-selma-al", permanent: true },
      { source: "/dumpster-rental-shawnee", destination: "/dumpster-rental-shawnee-ks", permanent: true },
      { source: "/dumpster-rental-sheffield", destination: "/dumpster-rental-sheffield-al", permanent: true },
      { source: "/dumpster-rental-shelton", destination: "/dumpster-rental-shelton-ct", permanent: true },
      { source: "/dumpster-rental-sherwood", destination: "/dumpster-rental-sherwood-ar", permanent: true },
      { source: "/dumpster-rental-shreveport", destination: "/dumpster-rental-shreveport-la", permanent: true },
      { source: "/dumpster-rental-sierra-vista", destination: "/dumpster-rental-sierra-vista-az", permanent: true },
      { source: "/dumpster-rental-simi-valley", destination: "/dumpster-rental-simi-valley-ca", permanent: true },
      { source: "/dumpster-rental-sioux-city", destination: "/dumpster-rental-sioux-city-ia", permanent: true },
      { source: "/dumpster-rental-skokie", destination: "/dumpster-rental-skokie-il", permanent: true },
      { source: "/dumpster-rental-slidell", destination: "/dumpster-rental-slidell-la", permanent: true },
      { source: "/dumpster-rental-smyrna", destination: "/dumpster-rental-smyrna-ga", permanent: true },
      { source: "/dumpster-rental-somerville", destination: "/dumpster-rental-somerville-ma", permanent: true },
      { source: "/dumpster-rental-south-bend", destination: "/dumpster-rental-south-bend-in", permanent: true },
      { source: "/dumpster-rental-south-jordan", destination: "/dumpster-rental-south-jordan-ut", permanent: true },
      { source: "/dumpster-rental-southaven", destination: "/dumpster-rental-southaven-ms", permanent: true },
      { source: "/dumpster-rental-southside", destination: "/dumpster-rental-southside-al", permanent: true },
      { source: "/dumpster-rental-spanish-fork", destination: "/dumpster-rental-spanish-fork-ut", permanent: true },
      { source: "/dumpster-rental-spanish-fort", destination: "/dumpster-rental-spanish-fort-al", permanent: true },
      { source: "/dumpster-rental-sparks", destination: "/dumpster-rental-sparks-nv", permanent: true },
      { source: "/dumpster-rental-spring-valley", destination: "/dumpster-rental-spring-valley-ny", permanent: true },
      { source: "/dumpster-rental-springdale", destination: "/dumpster-rental-springdale-ar", permanent: true },
      { source: "/dumpster-rental-springfield", destination: "/dumpster-rental-springfield-ma", permanent: true },
      { source: "/dumpster-rental-st-george", destination: "/dumpster-rental-st-george-ut", permanent: true },
      { source: "/dumpster-rental-st-louis", destination: "/dumpster-rental-st-louis-mo", permanent: true },
      { source: "/dumpster-rental-stamford", destination: "/dumpster-rental-stamford-ct", permanent: true },
      { source: "/dumpster-rental-starkville", destination: "/dumpster-rental-starkville-ms", permanent: true },
      { source: "/dumpster-rental-state-college", destination: "/dumpster-rental-state-college-pa", permanent: true },
      { source: "/dumpster-rental-stillwater", destination: "/dumpster-rental-stillwater-ok", permanent: true },
      { source: "/dumpster-rental-stockton", destination: "/dumpster-rental-stockton-ca", permanent: true },
      { source: "/dumpster-rental-strongsville", destination: "/dumpster-rental-strongsville-oh", permanent: true },
      { source: "/dumpster-rental-sugar-land", destination: "/dumpster-rental-sugar-land-tx", permanent: true },
      { source: "/dumpster-rental-sulphur", destination: "/dumpster-rental-sulphur-la", permanent: true },
      { source: "/dumpster-rental-sunnyvale", destination: "/dumpster-rental-sunnyvale-ca", permanent: true },
      { source: "/dumpster-rental-surprise", destination: "/dumpster-rental-surprise-az", permanent: true },
      { source: "/dumpster-rental-swiftwater", destination: "/dumpster-rental-swiftwater-pa", permanent: true },
      { source: "/dumpster-rental-sylacauga", destination: "/dumpster-rental-sylacauga-al", permanent: true },
      { source: "/dumpster-rental-syracuse", destination: "/dumpster-rental-syracuse-ny", permanent: true },
      { source: "/dumpster-rental-talladega", destination: "/dumpster-rental-talladega-al", permanent: true },
      { source: "/dumpster-rental-tarrytown", destination: "/dumpster-rental-tarrytown-ny", permanent: true },
      { source: "/dumpster-rental-taunton", destination: "/dumpster-rental-taunton-ma", permanent: true },
      { source: "/dumpster-rental-taylorsville", destination: "/dumpster-rental-taylorsville-ut", permanent: true },
      { source: "/dumpster-rental-tempe", destination: "/dumpster-rental-tempe-az", permanent: true },
      { source: "/dumpster-rental-terre-haute", destination: "/dumpster-rental-terre-haute-in", permanent: true },
      { source: "/dumpster-rental-texarkana", destination: "/dumpster-rental-texarkana-ar", permanent: true },
      { source: "/dumpster-rental-the-woodlands", destination: "/dumpster-rental-the-woodlands-tx", permanent: true },
      { source: "/dumpster-rental-thibodaux", destination: "/dumpster-rental-thibodaux-la", permanent: true },
      { source: "/dumpster-rental-thornton", destination: "/dumpster-rental-thornton-co", permanent: true },
      { source: "/dumpster-rental-thousand-oaks", destination: "/dumpster-rental-thousand-oaks-ca", permanent: true },
      { source: "/dumpster-rental-tigard", destination: "/dumpster-rental-tigard-or", permanent: true },
      { source: "/dumpster-rental-tinley-park", destination: "/dumpster-rental-tinley-park-il", permanent: true },
      { source: "/dumpster-rental-toledo", destination: "/dumpster-rental-toledo-oh", permanent: true },
      { source: "/dumpster-rental-topeka", destination: "/dumpster-rental-topeka-ks", permanent: true },
      { source: "/dumpster-rental-torrance", destination: "/dumpster-rental-torrance-ca", permanent: true },
      { source: "/dumpster-rental-troy", destination: "/dumpster-rental-troy-ny", permanent: true },
      { source: "/dumpster-rental-tucson", destination: "/dumpster-rental-tucson-az", permanent: true },
      { source: "/dumpster-rental-tulsa", destination: "/dumpster-rental-tulsa-ok", permanent: true },
      { source: "/dumpster-rental-tupelo", destination: "/dumpster-rental-tupelo-ms", permanent: true },
      { source: "/dumpster-rental-tuscaloosa", destination: "/dumpster-rental-tuscaloosa-al", permanent: true },
      { source: "/dumpster-rental-tuscumbia", destination: "/dumpster-rental-tuscumbia-al", permanent: true },
      { source: "/dumpster-rental-twin-falls", destination: "/dumpster-rental-twin-falls-id", permanent: true },
      { source: "/dumpster-rental-tyler", destination: "/dumpster-rental-tyler-tx", permanent: true },
      { source: "/dumpster-rental-utica", destination: "/dumpster-rental-utica-ny", permanent: true },
      { source: "/dumpster-rental-valdosta", destination: "/dumpster-rental-valdosta-ga", permanent: true },
      { source: "/dumpster-rental-vallejo", destination: "/dumpster-rental-vallejo-ca", permanent: true },
      { source: "/dumpster-rental-valley-stream", destination: "/dumpster-rental-valley-stream-ny", permanent: true },
      { source: "/dumpster-rental-vicksburg", destination: "/dumpster-rental-vicksburg-ms", permanent: true },
      { source: "/dumpster-rental-victorville", destination: "/dumpster-rental-victorville-ca", permanent: true },
      { source: "/dumpster-rental-virginia-beach", destination: "/dumpster-rental-virginia-beach-va", permanent: true },
      { source: "/dumpster-rental-visalia", destination: "/dumpster-rental-visalia-ca", permanent: true },
      { source: "/dumpster-rental-waco", destination: "/dumpster-rental-waco-tx", permanent: true },
      { source: "/dumpster-rental-wailuku", destination: "/dumpster-rental-wailuku-hi", permanent: true },
      { source: "/dumpster-rental-waipahu", destination: "/dumpster-rental-waipahu-hi", permanent: true },
      { source: "/dumpster-rental-wallingford", destination: "/dumpster-rental-wallingford-ct", permanent: true },
      { source: "/dumpster-rental-waltham", destination: "/dumpster-rental-waltham-ma", permanent: true },
      { source: "/dumpster-rental-warner-robins", destination: "/dumpster-rental-warner-robins-ga", permanent: true },
      { source: "/dumpster-rental-warren", destination: "/dumpster-rental-warren-oh", permanent: true },
      { source: "/dumpster-rental-waterbury", destination: "/dumpster-rental-waterbury-ct", permanent: true },
      { source: "/dumpster-rental-waterloo", destination: "/dumpster-rental-waterloo-ia", permanent: true },
      { source: "/dumpster-rental-waukegan", destination: "/dumpster-rental-waukegan-il", permanent: true },
      { source: "/dumpster-rental-west-dallas", destination: "/dumpster-rental-west-dallas-tx", permanent: true },
      { source: "/dumpster-rental-west-hartford", destination: "/dumpster-rental-west-hartford-ct", permanent: true },
      { source: "/dumpster-rental-west-haven", destination: "/dumpster-rental-west-haven-ct", permanent: true },
      { source: "/dumpster-rental-west-jordan", destination: "/dumpster-rental-west-jordan-ut", permanent: true },
      { source: "/dumpster-rental-west-monroe", destination: "/dumpster-rental-west-monroe-la", permanent: true },
      { source: "/dumpster-rental-west-sacramento", destination: "/dumpster-rental-west-sacramento-ca", permanent: true },
      { source: "/dumpster-rental-west-valley-city", destination: "/dumpster-rental-west-valley-city-ut", permanent: true },
      { source: "/dumpster-rental-westfield", destination: "/dumpster-rental-westfield-ma", permanent: true },
      { source: "/dumpster-rental-westminster", destination: "/dumpster-rental-westminster-co", permanent: true },
      { source: "/dumpster-rental-wheaton", destination: "/dumpster-rental-wheaton-il", permanent: true },
      { source: "/dumpster-rental-white-plains", destination: "/dumpster-rental-white-plains-ny", permanent: true },
      { source: "/dumpster-rental-wichita", destination: "/dumpster-rental-wichita-ks", permanent: true },
      { source: "/dumpster-rental-wilkes-barre", destination: "/dumpster-rental-wilkes-barre-pa", permanent: true },
      { source: "/dumpster-rental-williamsport", destination: "/dumpster-rental-williamsport-pa", permanent: true },
      { source: "/dumpster-rental-wilmington", destination: "/dumpster-rental-wilmington-nc", permanent: true },
      { source: "/dumpster-rental-winston-salem", destination: "/dumpster-rental-winston-salem-nc", permanent: true },
      { source: "/dumpster-rental-worcester", destination: "/dumpster-rental-worcester-ma", permanent: true },
      { source: "/dumpster-rental-yonkers", destination: "/dumpster-rental-yonkers-ny", permanent: true },
      { source: "/dumpster-rental-york", destination: "/dumpster-rental-york-pa", permanent: true },
      { source: "/dumpster-rental-youngstown", destination: "/dumpster-rental-youngstown-oh", permanent: true },
      { source: "/dumpster-rental-zachary", destination: "/dumpster-rental-zachary-la", permanent: true },
      // ============ MISC 404 FIXES ============
      { source: "/Brewers-Hill-Milwaukee-Wi", destination: "/dumpster-rental-milwaukee-wi", permanent: true },
      { source: "/dumpster-rental-augusta", destination: "/dumpster-rental-augusta-ga", permanent: true },
      { source: "/dumpster-rental-kansas-city", destination: "/dumpster-rental-kansas-city-mo", permanent: true },
      { source: "/cdn-cgi/:path*", destination: "/", permanent: false }, // Cloudflare paths
      { source: "/_next/static/css/:path*", destination: "/", permanent: false }, // Old CSS paths

      // ============ MALFORMED/CASE URLS ============
      { source: "/dumpster-rental-Costa-Mesa-CA", destination: "/dumpster-rental-costa-mesa-ca", permanent: true },
      { source: "/dumpster-rental-in-weston--fl", destination: "/dumpster-rental-weston", permanent: true },
      { source: "/dumpster-rental-in-weston-fl", destination: "/dumpster-rental-weston", permanent: true },
      { source: "/dumpster-rental-nationwide", destination: "/locations", permanent: true },

      // ============ CATCH-ALL: "in-" PREFIX PATTERN ============
      // Redirects /dumpster-rental-in-{city}-{state} to /dumpster-rental-{city}
      // This catches URLs like /dumpster-rental-in-miami-fl â†’ /dumpster-rental-miami
      { source: "/dumpster-rental-in-:city-fl", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-ca", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-tx", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-ny", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-ga", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-az", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-nc", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-oh", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-pa", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-il", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-mi", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-nj", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-va", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-wa", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-co", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-tn", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-wi", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-ma", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-md", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-mn", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-mo", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-in", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-sc", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-al", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-la", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-ky", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-or", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-ok", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-ct", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-nv", destination: "/dumpster-rental-:city", permanent: true },
      { source: "/dumpster-rental-in-:city-ut", destination: "/dumpster-rental-:city", permanent: true },

      // ============ 404 FIXES FROM GOOGLE SEARCH CONSOLE ============
      { source: "/st-johns-town-center", destination: "/dumpster-rental-jacksonville-fl", permanent: true },
      { source: "/dumpster-rental-fairfield", destination: "/locations", permanent: false },

      // ============ SLASH-SEPARATED DUMPSTER RENTAL URLS ============
      { source: "/dumpster-rental/:state", destination: "/dumpster-rental-:state", permanent: true },

      // ============ GENERIC NEIGHBORHOOD-CITY PATTERN ============
      { source: "/:slug*-neighborhood-:city", destination: "/locations", permanent: true },
    ];
  },
};

export default withNextIntl(nextConfig);
