import createMiddleware from 'next-intl/middleware';
import { NextRequest, NextResponse } from 'next/server';
import { locales, defaultLocale } from './i18n/config';

// Import CSS paths from build-time generated file
// NOTE: This file is generated by postbuild script (extract-css-paths.js)
// The paths are from the PREVIOUS build. This is intentional because:
// 1. Next.js bundles middleware at compile time (before postbuild runs)
// 2. CSS filenames rarely change between builds
// 3. Even if they do, old CSS files are still served for cache reasons
// For the very first deploy, linkHeader will be empty (no Early Hints)
import { linkHeader } from './generated/early-hints';

// Create next-intl middleware for i18n routing
const intlMiddleware = createMiddleware({
  locales,
  defaultLocale,
  localePrefix: 'as-needed', // Only show locale prefix for non-default locale
});

/**
 * Custom middleware that combines:
 * 1. next-intl i18n routing
 * 2. Cloudflare Early Hints Link headers for CSS preloading
 * 
 * Cloudflare caches Link headers from 200 responses and sends them
 * as 103 Early Hints to browsers, eliminating ~560ms of CSS delay.
 * 
 * IMPORTANT: After building locally, commit src/generated/early-hints.ts
 * This ensures Vercel deploys have the CSS paths baked in.
 */
export default function middleware(request: NextRequest): NextResponse {
  // Run next-intl middleware first
  const response = intlMiddleware(request);
  
  // Add Link headers for CSS preloading (Early Hints)
  // Only add for HTML page requests, not static assets
  const pathname = request.nextUrl.pathname;
  
    if (shouldAddEarlyHints(pathname) && linkHeader) {
    const existingLink = response.headers.get('Link');
    const newLink = existingLink ? `${existingLink}, ${linkHeader}` : linkHeader;
    response.headers.set('Link', newLink);
  }
  
  return response;
}

/**
 * Check if request should get Early Hints headers
 * Only HTML page responses need CSS preload hints
 */
function shouldAddEarlyHints(pathname: string): boolean {
  // Skip static assets, API routes, and internal Next.js paths
  if (
    pathname.startsWith('/_next/') ||
    pathname.startsWith('/api/') ||
    pathname.startsWith('/favicon') ||
    pathname.includes('.') // has file extension (images, fonts, etc.)
  ) {
    return false;
  }
  return true;
}

// Matcher: Run middleware on all routes except static files
// This is the standard pattern for next-intl with App Router
export const config = {
  matcher: [
    // Match all pathnames except for:
    // - /api (API routes)
    // - /_next (Next.js internals)
    // - /_vercel (Vercel internals)
    // - /static (custom static files)
    // - Files with extensions (.css, .js, .png, etc.)
    '/((?!api|_next|_vercel|.*\\..*).*)',
  ],
};
